# Generated by Django 5.0.2 on 2024-03-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeApp", "0002_alter_post_media"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="uploadedBy",
            new_name="author",
        ),
    ]
